server:
  port: 18080
  address: 10.107.119.52

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.107.108.227:3306/wecube_core_04?characterEncoding=utf8&serverTimezone=UTC
    username: wecube_core_04
    password: Abcd1234


wecube:
  core:
    cas-server-url: http://10.107.118.27:8080/cas
    cmdb-server-url: http://10.107.119.52:37000/cmdb
    plugin:
      plugin-hosts: 10.107.119.14,10.107.119.79
      plugin-package-name-of-deploy: salt-stack-deployment
